### ISSUE TITLE
Definition annotations

### ISSUE THREAD

**Issue by neilotte** [BFO-ontology/BFO-2020#7] opened 2020-12-31 16:21 UTC
1. Some of the definitions are marked as elucidations rather than definitions. Should these use an elucidation property rather than skos definition?
2. It appears the prefix declaration for skos is j.0. Suggest using '[skos](https://prefix.cc/skos)' instead.

**Comment by alanruttenberg** [comment] 2021-01-26 22:20
1. The benefit of having the user only have to know about a single skos-defined property outweighs the arguably more correct split into to two properties, one of which would have to be not skos. The "arguably" is that I'm sure actual use of the term has a substantial number of cases which aren't definitions as we understand them. Perhaps I should append "(elucidation)" to the end of the text for elucidations. Do you think I should? Another idea would be to have an extra annotation property that is a boolean "fully defined" or "elucidated". Having a new extra property means that uses can still query for skos:definition to get all the documentation, which is what they will expect. I think my preference would be to just leave it alone.
2. Prefix declarations are always local to a file. The j.0 prefix is automatically chosen by the OWL serialization code for serializations that use prefixes, but the prefixes themselves are not present in my functional syntax version that is created by my code, and the prefix skos: (or any prefix) is not mandated by the skos specification. I'll consider this a low priority "nice to have".

**Comment by alanruttenberg** [comment] 2021-08-28 20:51
The second point is duplicate of #21 and is fixed in the next release.

**Comment by alanruttenberg** [comment] 2021-09-01 03:29
The first point is addressed by adding (Elucidation) as a prefix for the skos:definition where appropriate. Fixed in the next release.

**Closed by alanruttenberg** 2021-09-01 03:29 UTC
